server:
  port: 1001
  context-path: /

mybatis:
  typeAliasesPackage:
  mapperLocations: classpath:mapper/*.xml

http:
  encoding.charset: UTF-8
  encoding.enable: true
  encoding.force: true

# 数据源配置
spring:
  application: 
    name: qiujie
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yijie?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
        host: 47.99.145.73
        port: 9527
        password: a0008612-
        timeout: 20000
        cluster:
            nodes: 47.101.152.186:9001,47.101.152.186:9002,47.101.152.186:9003,47.101.152.186:9004,47.101.152.186:9005,47.101.152.186:9006
            maxRedirects: 6
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
    
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: qiujie #客户端服务名
    instance-id: qiujie:1001 #客户端实例名称
    prefer-ip-address: true #显示IP
    lease-renewal-interval-in-seconds: 3600 #每间隔30s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 7300 #告诉服务端，如果我90s之内没有给你发心跳，就代表我“死”了，将我踢出掉

  client: 
    service-url: 
      # 单机
      #defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
#      defaultZone: http://eureka2001.marry.com:2001/eureka/,http://eureka2002.marry.com:2002/eureka/# 集群
      defaultZone: http://47.99.145.73:2001/eureka/,http://47.99.145.73:2002/eureka/ #集群
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: yyyyyyyyyqj
   联系电话: 56565656666
