
server:
  port: 88
  context-path: /

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 9000
  
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
            
eureka:
  client:
    service-url:
      #defaultZone: http://eureka2001.marry.com:2001/eureka/,http://eureka2002.marry.com:2002/eureka/
      defaultZone: http://47.99.145.73:2001/eureka/,http://47.99.145.73:2002/eureka/ #集群
spring:
  application:
    name: qiujie_consumer88

  